import org.junit.Test;

import static junit.framework.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jana' at '8/5/17 10:59 PM' with Gradle 2.10
 *
 * @author jana, @date 8/5/17 10:59 PM
 */
public class LibraryTest {

    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

}
