/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jana' at '8/5/17 10:59 PM' with Gradle 2.10
 *
 * @author jana, @date 8/5/17 10:59 PM
 */
public class Library {

    public boolean someLibraryMethod() {
        return true;
    }

}
